 /* OPERADORES DE COMPARAÇÃO
 > MAIOR
 >= MAIOR OU IGUAL
 < MENOR
 <= MENOR OU IGUAL
 == IGUALDADE(VALOR) NÃO USAR 
 === IGUALDADE ESTRITA(VALOR E TIPO)
 != DIFERENTE (VALOR) NÃO USAR
 !== DIFERENTE ESTRITO(VALOR E TIPO)
  */